knpu_oauth2_client:
    clients:
        google:
            type: google
            client_id: '%env(CRM_OAUTH_GOOGLE_CLIENT_ID)%'
            client_secret: '%env(CRM_OAUTH_GOOGLE_CLIENT_SECRET)%'
            redirect_route: user_google_auth
            redirect_params: {}
