security:
  encoders:
   app_encoder:
     algorithm: auto

  providers:
    database_users:
      entity: { class: App\Domain\Customer\Customer, property: email }

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      pattern: ^/api
      anonymous: true

  access_control:

  role_hierarchy:
    ROLE_ADMIN: ROLE_USER